// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.unicom.testDemo.putAndGetFromHbase;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ActorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string sex = 1;
    /**
     * <code>optional string sex = 1;</code>
     *
     * <pre>
     * 性别
     * </pre>
     */
    boolean hasSex();
    /**
     * <code>optional string sex = 1;</code>
     *
     * <pre>
     * 性别
     * </pre>
     */
    String getSex();
    /**
     * <code>optional string sex = 1;</code>
     *
     * <pre>
     * 性别
     * </pre>
     */
    com.google.protobuf.ByteString
        getSexBytes();

    // optional int32 score = 2;
    /**
     * <code>optional int32 score = 2;</code>
     *
     * <pre>
     * 得分
     * </pre>
     */
    boolean hasScore();
    /**
     * <code>optional int32 score = 2;</code>
     *
     * <pre>
     * 得分
     * </pre>
     */
    int getScore();

    // required int32 age = 3;
    /**
     * <code>required int32 age = 3;</code>
     *
     * <pre>
     * 年龄
     * </pre>
     */
    boolean hasAge();
    /**
     * <code>required int32 age = 3;</code>
     *
     * <pre>
     * 年龄
     * </pre>
     */
    int getAge();
  }
  /**
   * Protobuf type {@code com.unicom.testDemo.putAndGetFromHbase.Actor}
   *
   * <pre>
   *&#47;////////////////////////////////////////////////////////////////////////////
   * 手机号查询日表
   * 用户信息 日表 
   * 表: zhanggf_test
   * 列: f:mc
   * 数据样例 lizongsheng|男|90|50.0
   * rowkey: name,yyyyMMdd
   * </pre>
   */
  public static final class Actor extends
      com.google.protobuf.GeneratedMessage
      implements ActorOrBuilder {
    // Use Actor.newBuilder() to construct.
    private Actor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Actor(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Actor defaultInstance;
    public static Actor getDefaultInstance() {
      return defaultInstance;
    }

    public Actor getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Actor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sex_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              score_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              age_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Test.internal_static_com_unicom_testDemo_putAndGetFromHbase_Actor_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Test.internal_static_com_unicom_testDemo_putAndGetFromHbase_Actor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Actor.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Actor> PARSER =
        new com.google.protobuf.AbstractParser<Actor>() {
      public Actor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Actor(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Actor> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string sex = 1;
    public static final int SEX_FIELD_NUMBER = 1;
    private Object sex_;
    /**
     * <code>optional string sex = 1;</code>
     *
     * <pre>
     * 性别
     * </pre>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string sex = 1;</code>
     *
     * <pre>
     * 性别
     * </pre>
     */
    public String getSex() {
      Object ref = sex_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sex_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sex = 1;</code>
     *
     * <pre>
     * 性别
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSexBytes() {
      Object ref = sex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 score = 2;
    public static final int SCORE_FIELD_NUMBER = 2;
    private int score_;
    /**
     * <code>optional int32 score = 2;</code>
     *
     * <pre>
     * 得分
     * </pre>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 score = 2;</code>
     *
     * <pre>
     * 得分
     * </pre>
     */
    public int getScore() {
      return score_;
    }

    // required int32 age = 3;
    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>required int32 age = 3;</code>
     *
     * <pre>
     * 年龄
     * </pre>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 age = 3;</code>
     *
     * <pre>
     * 年龄
     * </pre>
     */
    public int getAge() {
      return age_;
    }

    private void initFields() {
      sex_ = "";
      score_ = 0;
      age_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSexBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, score_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, age_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSexBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, score_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Actor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Actor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Actor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Actor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Actor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Actor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Actor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Actor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Actor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Actor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Actor prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.unicom.testDemo.putAndGetFromHbase.Actor}
     *
     * <pre>
     *&#47;////////////////////////////////////////////////////////////////////////////
     * 手机号查询日表
     * 用户信息 日表 
     * 表: zhanggf_test
     * 列: f:mc
     * 数据样例 lizongsheng|男|90|50.0
     * rowkey: name,yyyyMMdd
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ActorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Test.internal_static_com_unicom_testDemo_putAndGetFromHbase_Actor_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Test.internal_static_com_unicom_testDemo_putAndGetFromHbase_Actor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Actor.class, Builder.class);
      }

      // Construct using com.unicom.testDemo.putAndGetFromHbase.Test.Actor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sex_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Test.internal_static_com_unicom_testDemo_putAndGetFromHbase_Actor_descriptor;
      }

      public Actor getDefaultInstanceForType() {
        return Actor.getDefaultInstance();
      }

      public Actor build() {
        Actor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Actor buildPartial() {
        Actor result = new Actor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.age_ = age_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Actor) {
          return mergeFrom((Actor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Actor other) {
        if (other == Actor.getDefaultInstance()) return this;
        if (other.hasSex()) {
          bitField0_ |= 0x00000001;
          sex_ = other.sex_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAge()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Actor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Actor) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string sex = 1;
      private Object sex_ = "";
      /**
       * <code>optional string sex = 1;</code>
       *
       * <pre>
       * 性别
       * </pre>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string sex = 1;</code>
       *
       * <pre>
       * 性别
       * </pre>
       */
      public String getSex() {
        Object ref = sex_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sex_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string sex = 1;</code>
       *
       * <pre>
       * 性别
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sex = 1;</code>
       *
       * <pre>
       * 性别
       * </pre>
       */
      public Builder setSex(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sex = 1;</code>
       *
       * <pre>
       * 性别
       * </pre>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sex_ = getDefaultInstance().getSex();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sex = 1;</code>
       *
       * <pre>
       * 性别
       * </pre>
       */
      public Builder setSexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sex_ = value;
        onChanged();
        return this;
      }

      // optional int32 score = 2;
      private int score_ ;
      /**
       * <code>optional int32 score = 2;</code>
       *
       * <pre>
       * 得分
       * </pre>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 score = 2;</code>
       *
       * <pre>
       * 得分
       * </pre>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>optional int32 score = 2;</code>
       *
       * <pre>
       * 得分
       * </pre>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000002;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 score = 2;</code>
       *
       * <pre>
       * 得分
       * </pre>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0;
        onChanged();
        return this;
      }

      // required int32 age = 3;
      private int age_ ;
      /**
       * <code>required int32 age = 3;</code>
       *
       * <pre>
       * 年龄
       * </pre>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 age = 3;</code>
       *
       * <pre>
       * 年龄
       * </pre>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>required int32 age = 3;</code>
       *
       * <pre>
       * 年龄
       * </pre>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000004;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 age = 3;</code>
       *
       * <pre>
       * 年龄
       * </pre>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.unicom.testDemo.putAndGetFromHbase.Actor)
    }

    static {
      defaultInstance = new Actor(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.unicom.testDemo.putAndGetFromHbase.Actor)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_unicom_testDemo_putAndGetFromHbase_Actor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_unicom_testDemo_putAndGetFromHbase_Actor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ntest.proto\022&com.unicom.testDemo.putAnd" +
      "GetFromHbase\"0\n\005Actor\022\013\n\003sex\030\001 \001(\t\022\r\n\005sc" +
      "ore\030\002 \001(\005\022\013\n\003age\030\003 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_unicom_testDemo_putAndGetFromHbase_Actor_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_unicom_testDemo_putAndGetFromHbase_Actor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_unicom_testDemo_putAndGetFromHbase_Actor_descriptor,
              new String[] { "Sex", "Score", "Age", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
